#!/bin/bash

if [ ! -d "build" ];then
  mkdir build
fi

if [ -d "Example/$1" ]
then
  cc source/*.c Example/$1/main.c -I ./include -o build/$1
  cd build
  ./$1
else
  echo "Example does not exists."
  echo "Example list :"
  echo `ls Example`
fi
